export const ErrorCodes = {
  // Generic / Infrastructure
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  RATE_LIMITED: 'RATE_LIMITED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',

  // Domain / Lifecycle Error Codes (from Phase 0.4 API Spec)
  AUTHENTICATION_FAILED: 'AUTHENTICATION_FAILED',
  ACCESS_FORBIDDEN: 'ACCESS_FORBIDDEN',
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  INVENTORY_CAPACITY_EXCEEDED: 'INVENTORY_CAPACITY_EXCEEDED',
  INVENTORY_HOLD_EXPIRED: 'INVENTORY_HOLD_EXPIRED',
  PAYMENT_GATEWAY_REJECTED: 'PAYMENT_GATEWAY_REJECTED',
  PAYMENT_WEBHOOK_SIGNATURE_INVALID: 'PAYMENT_WEBHOOK_SIGNATURE_INVALID',
  CANCELLATION_INELIGIBLE: 'CANCELLATION_INELIGIBLE',
  DOCUMENT_GENERATION_FAILED: 'DOCUMENT_GENERATION_FAILED',
  CONCURRENT_MUTATION_CONFLICT: 'CONCURRENT_MUTATION_CONFLICT',

  // Booking Engine Error Codes (Phase 5)
  BOOKING_NOT_FOUND: 'BOOKING_NOT_FOUND',
  BOOKING_ALREADY_CANCELLED: 'BOOKING_ALREADY_CANCELLED',
  BOOKING_INVALID_STATE: 'BOOKING_INVALID_STATE',
  HOLD_NOT_FOUND: 'HOLD_NOT_FOUND',
  IDEMPOTENCY_CONFLICT: 'IDEMPOTENCY_CONFLICT',

  // Payment, Document & Refund Error Codes (Phase 6)
  PAYMENT_NOT_FOUND: 'PAYMENT_NOT_FOUND',
  PAYMENT_INVALID_STATE: 'PAYMENT_INVALID_STATE',
  PAYMENT_ALREADY_PROCESSED: 'PAYMENT_ALREADY_PROCESSED',
  PAYMENT_AMOUNT_MISMATCH: 'PAYMENT_AMOUNT_MISMATCH',
  PAYMENT_CURRENCY_MISMATCH: 'PAYMENT_CURRENCY_MISMATCH',
  PAYMENT_PROVIDER_ERROR: 'PAYMENT_PROVIDER_ERROR',
  PAYMENT_VERIFICATION_FAILED: 'PAYMENT_VERIFICATION_FAILED',
  WEBHOOK_EVENT_DUPLICATE: 'WEBHOOK_EVENT_DUPLICATE',
  REFUND_FAILED: 'REFUND_FAILED',
  REFUND_INVALID_STATE: 'REFUND_INVALID_STATE',
  DOCUMENT_NOT_FOUND: 'DOCUMENT_NOT_FOUND',
  DOCUMENT_ACCESS_DENIED: 'DOCUMENT_ACCESS_DENIED',
  CANCELLATION_REQUEST_NOT_FOUND: 'CANCELLATION_REQUEST_NOT_FOUND',

  // Admin, CMS & Operations Error Codes (Phase 7)
  HERO_SLIDER_NOT_FOUND: 'HERO_SLIDER_NOT_FOUND',
  CMS_PAGE_NOT_FOUND: 'CMS_PAGE_NOT_FOUND',
  AUDIT_LOG_NOT_FOUND: 'AUDIT_LOG_NOT_FOUND',

  // Notification Error Codes (Phase 8)
  NOTIFICATION_NOT_FOUND: 'NOTIFICATION_NOT_FOUND',
  NOTIFICATION_DELIVERY_FAILED: 'NOTIFICATION_DELIVERY_FAILED',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
